/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class frmChinh extends javax.swing.JFrame {

    /**
     * Creates new form frmChinh
     */
    public frmChinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlFrmTD = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        lblSeach = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        hover5 = new javax.swing.JPanel();
        lblHover5 = new javax.swing.JLabel();
        hover3 = new javax.swing.JPanel();
        lblHover3 = new javax.swing.JLabel();
        hover2 = new javax.swing.JPanel();
        lblHover2 = new javax.swing.JLabel();
        hover1 = new javax.swing.JPanel();
        lblHover1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCtyHangDau = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        VLCty1 = new javax.swing.JLabel();
        TenCtyLg1 = new javax.swing.JLabel();
        lg1 = new javax.swing.JLabel();
        lg2 = new javax.swing.JLabel();
        VLCty2 = new javax.swing.JLabel();
        TenCtyLg2 = new javax.swing.JLabel();
        lg3 = new javax.swing.JLabel();
        VLCty3 = new javax.swing.JLabel();
        TenCtyLg3 = new javax.swing.JLabel();
        lg4 = new javax.swing.JLabel();
        VLCty4 = new javax.swing.JLabel();
        TenCty4 = new javax.swing.JLabel();
        lg5 = new javax.swing.JLabel();
        lg6 = new javax.swing.JLabel();
        VLCty5 = new javax.swing.JLabel();
        TenCty5 = new javax.swing.JLabel();
        VLCty6 = new javax.swing.JLabel();
        TenCty6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnlFrmTD.setBackground(new java.awt.Color(255, 255, 255));
        pnlFrmTD.setPreferredSize(new java.awt.Dimension(1221, 1300));

        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tìm kiếm công việc mơ ước");
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 330, 40));

        txtTimKiem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTimKiem.setBorder(null);
        header.add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 390, 40));

        lblSeach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seach.png"))); // NOI18N
        header.add(lblSeach, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 595, 40));

        lblHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/header.png"))); // NOI18N
        header.add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnTimKiem.setText("jButton1");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        header.add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 160, 40));

        btnLogin.setText("jButton1");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        header.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 3, 50, 50));

        hover5.setBackground(new java.awt.Color(0, 185, 242));
        hover5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hover5MouseExited(evt);
            }
        });

        lblHover5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hover.png"))); // NOI18N

        javax.swing.GroupLayout hover5Layout = new javax.swing.GroupLayout(hover5);
        hover5.setLayout(hover5Layout);
        hover5Layout.setHorizontalGroup(
            hover5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHover5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        hover5Layout.setVerticalGroup(
            hover5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hover5Layout.createSequentialGroup()
                .addGap(0, 58, Short.MAX_VALUE)
                .addComponent(lblHover5))
        );

        header.add(hover5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 110, 60));

        hover3.setBackground(new java.awt.Color(0, 185, 242));
        hover3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hover3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hover3MouseExited(evt);
            }
        });

        lblHover3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hover.png"))); // NOI18N

        javax.swing.GroupLayout hover3Layout = new javax.swing.GroupLayout(hover3);
        hover3.setLayout(hover3Layout);
        hover3Layout.setHorizontalGroup(
            hover3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHover3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        hover3Layout.setVerticalGroup(
            hover3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hover3Layout.createSequentialGroup()
                .addGap(0, 58, Short.MAX_VALUE)
                .addComponent(lblHover3))
        );

        header.add(hover3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 110, 60));

        hover2.setBackground(new java.awt.Color(0, 185, 242));
        hover2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hover2MouseExited(evt);
            }
        });

        lblHover2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hover.png"))); // NOI18N

        javax.swing.GroupLayout hover2Layout = new javax.swing.GroupLayout(hover2);
        hover2.setLayout(hover2Layout);
        hover2Layout.setHorizontalGroup(
            hover2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHover2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        hover2Layout.setVerticalGroup(
            hover2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hover2Layout.createSequentialGroup()
                .addGap(0, 58, Short.MAX_VALUE)
                .addComponent(lblHover2))
        );

        header.add(hover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 110, 60));

        hover1.setBackground(new java.awt.Color(0, 185, 242));
        hover1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hover1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hover1MouseExited(evt);
            }
        });

        lblHover1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hover.png"))); // NOI18N

        javax.swing.GroupLayout hover1Layout = new javax.swing.GroupLayout(hover1);
        hover1.setLayout(hover1Layout);
        hover1Layout.setHorizontalGroup(
            hover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHover1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        hover1Layout.setVerticalGroup(
            hover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hover1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(lblHover1))
        );

        header.add(hover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 110, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblCtyHangDau.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCtyHangDau.setText("CÁC CÔNG TY HÀNG ĐẦU");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vnpt.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mater.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lotte.png"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/uni.png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel7.setForeground(new java.awt.Color(0, 204, 255));
        jLabel7.setText("VNPT CUỘC SỐNG ĐÍCH THỰC");

        jLabel8.setForeground(new java.awt.Color(0, 204, 255));
        jLabel8.setText("CHO CUỘC SỐNG BỪNG SÁNG");

        jLabel9.setForeground(new java.awt.Color(0, 204, 255));
        jLabel9.setText("MASTERISE GROUP");

        jLabel10.setForeground(new java.awt.Color(0, 204, 255));
        jLabel10.setText("LIFETIME VALUE CREATOR");

        jLabel11.setForeground(new java.awt.Color(0, 204, 255));
        jLabel11.setText("TO ADD VITALITY TO LIFE");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/novaLane.png"))); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(451, 451, 451)
                        .addComponent(lblCtyHangDau))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jLabel7)
                                .addGap(62, 62, 62)
                                .addComponent(jLabel8)
                                .addGap(89, 89, 89))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(103, 103, 103)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(83, 83, 83)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel11)))))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblCtyHangDau, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addGap(0, 69, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VLCty1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VLCty1.setText("Chuyên Viên Telesale Level Cao");
        jPanel2.add(VLCty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 330, 30));

        TenCtyLg1.setText("CÔNG TY CỔ PHẦN GIÁO DỤC EDUCA CORPORATION");
        jPanel2.add(TenCtyLg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 330, 30));

        lg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lg1.png"))); // NOI18N
        jPanel2.add(lg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 80, 60));

        lg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lg2.png"))); // NOI18N
        jPanel2.add(lg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 80, 70));

        VLCty2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VLCty2.setText("Senior Design Engineer");
        jPanel2.add(VLCty2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 330, 30));

        TenCtyLg2.setText("CÔNG TY TNHH ACTIVE-SEMI VIỆT NAM (QORVO)");
        jPanel2.add(TenCtyLg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 330, 20));

        lg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lg3.png"))); // NOI18N
        jPanel2.add(lg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 80, 50));

        VLCty3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VLCty3.setText("PHP Developer Game");
        jPanel2.add(VLCty3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 330, 20));

        TenCtyLg3.setText("CÔNG TY TNHH ATEAM VIỆT NAM");
        jPanel2.add(TenCtyLg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 330, -1));

        lg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lg4.png"))); // NOI18N
        jPanel2.add(lg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 80, 40));

        VLCty4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VLCty4.setText("QA Game Tester (All Levels)");
        jPanel2.add(VLCty4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 320, -1));

        TenCty4.setText("NEXON-NETWORKS VINA");
        jPanel2.add(TenCty4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 320, -1));

        lg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lg5.png"))); // NOI18N
        jPanel2.add(lg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 80, 40));

        lg6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lg6.png"))); // NOI18N
        jPanel2.add(lg6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 80, 30));

        VLCty5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VLCty5.setText(" [Viện Big Data] Frontend Engineer");
        jPanel2.add(VLCty5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 310, -1));

        TenCty5.setText("VIỆN NGHIÊN CỨU DỮ LIỆU LỚN VINBIGDATA");
        jPanel2.add(TenCty5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 320, -1));

        VLCty6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VLCty6.setText("Nhân Viên Giáo Vụ");
        jPanel2.add(VLCty6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, 320, -1));

        TenCty6.setText("VIETNAM AUSTRALIA INTERNATIONAL SCHOOL (VAS)");
        jPanel2.add(TenCty6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 320, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Việc làm tốt nhất");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1083, 330, 110, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/vltn.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 926, 289));

        javax.swing.GroupLayout pnlFrmTDLayout = new javax.swing.GroupLayout(pnlFrmTD);
        pnlFrmTD.setLayout(pnlFrmTDLayout);
        pnlFrmTDLayout.setHorizontalGroup(
            pnlFrmTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFrmTDLayout.createSequentialGroup()
                .addGroup(pnlFrmTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 1211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFrmTDLayout.setVerticalGroup(
            pnlFrmTDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFrmTDLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(pnlFrmTD);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setColor(JPanel p){
        p.setBackground(new Color(255,255,255));
    }
    
    public void resetColor(JPanel p){
        p.setBackground(new Color(ERROR, rootPaneCheckingEnabled));
    }
    
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        JOptionPane.showMessageDialog(this, "Tên đăng nhập phải từ 6 ký thự trở lên");
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void hover1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover1MouseEntered
        lblHover1.setVisible(true);
    }//GEN-LAST:event_hover1MouseEntered
        
    private void hover1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover1MouseExited
        lblHover1.setVisible(false);
    }//GEN-LAST:event_hover1MouseExited

    private void hover2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover2MouseEntered
        lblHover2.setVisible(true);
    }//GEN-LAST:event_hover2MouseEntered

    private void hover2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover2MouseExited
        lblHover2.setVisible(false);
    }//GEN-LAST:event_hover2MouseExited

    private void hover3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover3MouseEntered
        lblHover3.setVisible(true);
    }//GEN-LAST:event_hover3MouseEntered

    private void hover3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover3MouseExited
        lblHover3.setVisible(false);
    }//GEN-LAST:event_hover3MouseExited

    private void hover5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover5MouseEntered
        lblHover5.setVisible(true);
    }//GEN-LAST:event_hover5MouseEntered

    private void hover5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover5MouseExited
         lblHover5.setVisible(false);
    }//GEN-LAST:event_hover5MouseExited

    private void hover1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover1MouseClicked
         frmDanhSachViecLam DSVL = new frmDanhSachViecLam();
         DSVL.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_hover1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int rs = JOptionPane.showConfirmDialog(this, "bạn có muốn thoát không", "cảnh báo thoát", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (rs == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        frmLogin login = new frmLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void hover3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover3MouseClicked
        frmDanhSachViecLam DSCTY = new frmDanhSachViecLam();
         DSCTY.setVisible(true);
         this.dispose();
        
    }//GEN-LAST:event_hover3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TenCty4;
    private javax.swing.JLabel TenCty5;
    private javax.swing.JLabel TenCty6;
    private javax.swing.JLabel TenCtyLg1;
    private javax.swing.JLabel TenCtyLg2;
    private javax.swing.JLabel TenCtyLg3;
    private javax.swing.JLabel VLCty1;
    private javax.swing.JLabel VLCty2;
    private javax.swing.JLabel VLCty3;
    private javax.swing.JLabel VLCty4;
    private javax.swing.JLabel VLCty5;
    private javax.swing.JLabel VLCty6;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JPanel header;
    private javax.swing.JPanel hover1;
    private javax.swing.JPanel hover2;
    private javax.swing.JPanel hover3;
    private javax.swing.JPanel hover5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCtyHangDau;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHover1;
    private javax.swing.JLabel lblHover2;
    private javax.swing.JLabel lblHover3;
    private javax.swing.JLabel lblHover5;
    private javax.swing.JLabel lblSeach;
    private javax.swing.JLabel lg1;
    private javax.swing.JLabel lg2;
    private javax.swing.JLabel lg3;
    private javax.swing.JLabel lg4;
    private javax.swing.JLabel lg5;
    private javax.swing.JLabel lg6;
    private javax.swing.JPanel pnlFrmTD;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
